# -*- coding: utf-8 -*-
# Developed by Bizople Solutions Pvt. Ltd.
# See LICENSE file for full copyright and licensing details

{
    'name': 'Theme Snazzy',
    'category': 'Theme/eCommerce',
    'version': '14.0.0.0',
    'author': 'Bizople Solutions Pvt. Ltd.',
    'website': 'https://www.bizople.com',
    'summary': 'Theme Snazzy is featured with eCommerce functionalities and is fully responsive for all devices that can be used for Electronics, Furniture, Cosmetics, and related industries.',    
    'description': """Theme Snazzy is featured with eCommerce functionalities and is fully responsive for all devices that can be used for Electronics, Furniture, Cosmetics, and related industries.""",
    'depends': [
        'snazzy_theme_common',
    ],

    'data': [
            'views/assets.xml',
            'views/customize_inherit.xml',
            'views/ecommerce_templates.xml',
            'views/shop_page_template.xml',
            'views/product_customize_template.xml',
            'views/product_page_template.xml',
            'views/product_banner_options.xml',
            'views/res_config.xml',
            'views/brand_view.xml',
            'views/coming_soon_template.xml',
            'views/404_template.xml',
            'views/thankyou_template.xml',
            'views/help_center_template.xml',
            'views/product_quick_view_template.xml',
            'views/pwa_shortcuts.xml',
            'views/dynamicslider.xml',
            'views/product_tab_view.xml',
            'views/product_service_view.xml',
            'views/product_pricelist_view.xml',
            'views/theme_snazzy_inherited.xml',
            'views/theme_snazzy_search.xml',
            'views/product_template_attribute_value_view.xml',
            'views/product_page_variant_img_template.xml',
            'views/product_compare_inherited.xml',
            'views/image_hotspot_options.xml',
            'views/snippet_options.xml',
            'views/shop_cart_sidebar.xml',
            'views/portal_template.xml',
            'views/sale_portal_templates_inherit.xml',
            'views/store_location.xml',
            'views/shop_outlets_template.xml',
            'views/checkout_pages_inherit.xml',
            'views/wishlist_page_inherited.xml',
            'views/saleorder_field_add.xml',
            'views/login_template_inherited.xml',
            'views/dynamic_config_template.xml',
            'views/configurator/product_configurator_template.xml',
            'views/configurator/category_configurator_template.xml',
            'views/configurator/brand_configurator_template.xml',
            'views/configurator/blog_configurator_template.xml',
            'views/menus.xml',
            
            # Inherited
            'views/inherited/blog_page_inherit.xml',
            'views/inherited/contact_us_template.xml',
            
            # Homepage
            'views/homepages/electronic_homepage.xml',
            'views/homepages/furniture_homepage.xml',
            'views/homepages/shoes_homepage.xml',
            'views/homepages/cosmetic_homepage.xml',
            'views/homepages/typographys.xml',
            'views/homepages/offer_page.xml',

            # Headers
            'views/headers/header_common_template.xml',
            'views/headers/header_template1.xml',
            'views/headers/header_template2.xml',
            'views/headers/header_template3.xml',
            'views/headers/header_template4.xml',
            'views/headers/header_template5.xml',
            'views/headers/header_template6.xml',
            
            # Footers
            'views/footers/footer_template1.xml',
            'views/footers/footer_template2.xml',
            'views/footers/footer_template3.xml',
            'views/footers/footer_template4.xml',
            'views/footers/footer_template5.xml',
            'views/footers/footer_template6.xml',
            'views/footers/footer_template7.xml',
            'views/footers/footer_template8.xml',
            'views/footers/footer_template9.xml',

            # snippets
            'views/snippets/s_theme_snazzy_page_one.xml',
            'views/snippets/s_theme_snazzy_page_two.xml',
            'views/snippets/s_theme_snazzy_page_three.xml',
            'views/snippets/s_theme_snazzy_page_four.xml',

            'views/snippets/s_biz_theme_snazzy_homepage_one_banner.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_banner_one.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_two_block_three_img.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_countdown_two_block.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_limited_edition_one.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_limited_edition_two.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_two_block_img.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_game_controller.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_new_arrivals_text_style.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_product_add_to_cart.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_hotspot_image.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_testimonial.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_news_letter.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_order_features.xml',

            'views/snippets/s_biz_theme_snazzy_two_banner_one.xml',
            'views/snippets/s_biz_theme_snazzy_two_banner_two.xml',
            'views/snippets/s_biz_theme_snazzy_two_better_quality.xml',
            'views/snippets/s_biz_theme_snazzy_two_hot_this_week.xml',
            'views/snippets/s_biz_theme_snazzy_two_our_story.xml',
            'views/snippets/s_biz_theme_snazzy_two_super_quality_shoes.xml',
            'views/snippets/s_biz_theme_snazzy_two_best_feature_in_shoes.xml',
            'views/snippets/s_biz_theme_snazzy_two_hostport_image.xml',
            'views/snippets/s_biz_theme_snazzy_two_special_offer.xml',
            'views/snippets/s_biz_theme_snazzy_two_order_features.xml',
            'views/snippets/s_biz_theme_snazzy_two_gallery.xml',
            'views/snippets/s_biz_theme_snazzy_two_hover_img_effect.xml',

            'views/snippets/s_biz_theme_snazzy_three_banner.xml',
            'views/snippets/s_biz_theme_snazzy_three_discover_our_collection.xml',
            'views/snippets/s_biz_theme_snazzy_three_new_collection.xml',
            'views/snippets/s_biz_theme_snazzy_three_wooden_bed.xml',
            'views/snippets/s_biz_theme_snazzy_three_hostport_image.xml',
            'views/snippets/s_biz_theme_snazzy_three_reviews_carousel.xml',
            'views/snippets/s_biz_theme_snazzy_three_get_inspired.xml',

            'views/snippets/s_biz_theme_snazzy_four_banner.xml',
            'views/snippets/s_biz_theme_snazzy_four_popular_categories.xml',
            'views/snippets/s_biz_theme_snazzy_four_countdown_two_block.xml',
            'views/snippets/s_biz_theme_snazzy_four_order_features.xml',
            'views/snippets/s_biz_theme_snazzy_four_unique_needs_two_block.xml',
            'views/snippets/s_biz_theme_snazzy_four_about_video.xml',
            'views/snippets/s_biz_theme_snazzy_four_new_arrivals_text_style.xml',
            'views/snippets/s_biz_theme_snazzy_four_testimonial.xml',

            'views/snippets/s_configurator_snippet_style1.xml',
            'views/snippets/s_configurator_snippet_style2.xml',
            'views/snippets/s_configurator_snippet_style3.xml',
            'views/snippets/s_configurator_snippet_style4.xml',
            'views/snippets/s_configurator_snippet_style5.xml',
            'views/snippets/s_configurator_snippet_style6.xml',
            'views/snippets/s_configurator_snippet_style7.xml',
            'views/snippets/s_configurator_snippet_style8.xml',
            'views/snippets/s_configurator_snippet_style9.xml',
            'views/snippets/s_configurator_snippet_style10.xml',
            'views/snippets/snazzy_newsletter_subscribe_popup.xml',
            'views/snippets/snazzy_offer_popup.xml',
    ],

    'demo': [
        'data/menu_data.xml',
    ],

    'live_test_url': 'https://bit.ly/theme-snazzy-bizople',

    'images': [
        'static/description/snazzy_cover.jpg',
        'static/description/snazzy_screenshot.gif',
    ],
    
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'OPL-1',
    'price': 165,
    'currency': 'EUR',
}
